/*
 * This file is part of mcav, a media playback library for Java
 * Copyright (C) Brandon Li <https://brandonli.me/>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package me.brandonli.mcav.media.player.image;

import com.google.common.base.Preconditions;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.ForkJoinPool;
import me.brandonli.mcav.media.player.ReleasablePlayer;
import me.brandonli.mcav.media.player.attachable.VideoAttachableCallback;
import me.brandonli.mcav.media.player.multimedia.ExceptionHandler;
import me.brandonli.mcav.media.source.frame.FrameSource;

/**
 * Plays frames generated by code, such as animated GIFs decoded with
 * {@link me.brandonli.mcav.media.image.DynamicImageBuffer} or live captures, through a video pipeline at the
 * frame rate of the source.
 *
 * <pre><code>
 *   final ImagePlayer player = ImagePlayer.player();
 *   final VideoAttachableCallback video = player.getVideoAttachableCallback();
 *   video.attach(pipeline);
 *   final RepeatingFrameSource source = RepeatingFrameSource.repeating(gif);
 *   player.start(source);
 * </code></pre>
 */
public interface ImagePlayer extends ReleasablePlayer, ExceptionHandler {
  /**
   * Creates a player.
   *
   * @return the player
   */
  static ImagePlayer player() {
    return new ImagePlayerImpl();
  }

  /**
   * Starts pulling frames from a source. A player plays one source at a time; release it or wait for
   * {@link #release()} before starting another.
   *
   * @param source the source of frames
   * @return true if playback started, false if the player is already playing or released
   */
  boolean start(final FrameSource source);

  /**
   * Starts playback on an executor.
   *
   * @param source   the source of frames
   * @param executor the executor that runs the call
   * @return a future that completes with the result of {@link #start(FrameSource)}
   */
  default CompletableFuture<Boolean> startAsync(final FrameSource source, final ExecutorService executor) {
    Preconditions.checkNotNull(source, "Source must not be null");
    Preconditions.checkNotNull(executor, "Executor must not be null");
    return CompletableFuture.supplyAsync(() -> this.start(source), executor);
  }

  /**
   * Starts playback on the common pool.
   *
   * @param source the source of frames
   * @return a future that completes with the result of {@link #start(FrameSource)}
   */
  default CompletableFuture<Boolean> startAsync(final FrameSource source) {
    final ForkJoinPool pool = ForkJoinPool.commonPool();
    return this.startAsync(source, pool);
  }

  /**
   * Gets the slot that holds the video pipeline.
   *
   * @return the video pipeline slot
   */
  VideoAttachableCallback getVideoAttachableCallback();
}
