/*
 * This file is part of mcav, a media playback library for Java
 * Copyright (C) Brandon Li <https://brandonli.me/>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package me.brandonli.mcav.media.source.frame;

import com.google.common.base.Preconditions;
import me.brandonli.mcav.media.source.DynamicSource;

/**
 * Frames generated by code, such as a screen capture, a game render, or an animation, for playback with
 * {@link me.brandonli.mcav.media.player.image.ImagePlayer}.
 *
 * <p>The player asks the supplier for a frame at the frame rate of the source. Suppliers that have no new frame
 * may return the previous one or an empty array, which is skipped.
 */
public interface FrameSource extends DynamicSource {
  /**
   * The frame rate used when none is specified.
   */
  float DEFAULT_FRAME_RATE = 30.0f;

  /**
   * Creates a frame source from an image supplier.
   *
   * @param images the supplier of frames
   * @param width  the width of the frames in pixels
   * @param height the height of the frames in pixels
   * @return the source, played at {@link #DEFAULT_FRAME_RATE}
   */
  static FrameSource image(final ImageSupplier images, final int width, final int height) {
    Preconditions.checkNotNull(images, "Image supplier must not be null");
    final SampleSupplier samples = images.toSampleSupplier();
    return supplier(samples, width, height, DEFAULT_FRAME_RATE);
  }

  /**
   * Creates a frame source from a pixel supplier.
   *
   * @param supplier the supplier of frames
   * @param width    the width of the frames in pixels
   * @param height   the height of the frames in pixels
   * @return the source, played at {@link #DEFAULT_FRAME_RATE}
   */
  static FrameSource supplier(final SampleSupplier supplier, final int width, final int height) {
    return supplier(supplier, width, height, DEFAULT_FRAME_RATE);
  }

  /**
   * Creates a frame source from a pixel supplier with a frame rate.
   *
   * @param supplier  the supplier of frames
   * @param width     the width of the frames in pixels
   * @param height    the height of the frames in pixels
   * @param frameRate the frame rate in frames per second
   * @return the source
   */
  static FrameSource supplier(final SampleSupplier supplier, final int width, final int height, final float frameRate) {
    Preconditions.checkNotNull(supplier, "Sample supplier must not be null");
    Preconditions.checkArgument(width > 0 && height > 0, "Frame size must be positive");
    Preconditions.checkArgument(frameRate > 0 && Float.isFinite(frameRate), "Frame rate must be positive");
    return new FrameSourceImpl(supplier, width, height, frameRate);
  }

  /**
   * Gets the supplier of frames.
   *
   * @return the supplier
   */
  SampleSupplier supplyFrameSamples();

  /**
   * Gets the width of the frames.
   *
   * @return the width in pixels
   */
  int getFrameWidth();

  /**
   * Gets the height of the frames.
   *
   * @return the height in pixels
   */
  int getFrameHeight();

  /**
   * Gets the rate at which frames are requested from the supplier.
   *
   * @return the frame rate in frames per second
   */
  default float getFrameRate() {
    return DEFAULT_FRAME_RATE;
  }

  @Override
  default String getName() {
    return "frame-source";
  }

  @Override
  default String getResource() {
    final int width = this.getFrameWidth();
    final int height = this.getFrameHeight();
    final float frameRate = this.getFrameRate();
    return width + "x" + height + "@" + frameRate;
  }
}
