/*
 * This file is part of mcav, a media playback library for Java
 * Copyright (C) Brandon Li <https://brandonli.me/>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package me.brandonli.mcav.mod;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;
import org.junit.jupiter.api.Test;

final class PackLayoutTest {

  /** A layout as the server generates it, with the stream ids, slot counts and first slots of its screens. */
  static String packConstants(final String streams, final String slots, final String firsts, final int screens) {
    return String.join(
      "\n",
      "#ifndef MCAV_MCV2_CONFIG_GLSL",
      "#define MCAV_MCV2_CONFIG_GLSL",
      "// Generated by mcav for the MCV2 screens of one pack.",
      "const int MCV2_SCREENS = " + screens + ";",
      "const int MCV2_TOTAL_SLOTS = 5;",
      "const uint MCV2_SCREEN_STREAMS[" + screens + "] = uint[" + screens + "](" + streams + ");",
      "const int MCV2_SCREEN_SLOTS[" + screens + "] = int[" + screens + "](" + slots + ");",
      "const int MCV2_SCREEN_FIRST_SLOTS[" + screens + "] = int[" + screens + "](" + firsts + ");",
      "const bool MCV2_DEBUG_VIEW = false;",
      "const ivec3 MCV2_OUTLINE_COLOR = ivec3(1, 2, 3);",
      "#endif",
      ""
    );
  }

  @Test
  void readsTheScreensTheServerGenerated() {
    final PackLayout layout = PackLayout.parse(packConstants("7u, 4294967295u", "3, 2", "0, 3", 2)).orElseThrow();
    assertEquals(2, layout.screens());
    assertEquals(3, layout.slots(0));
    assertEquals(2, layout.slots(1));
    assertEquals(0, layout.firstSlot(0));
    assertEquals(3, layout.firstSlot(1));
    assertEquals(5, layout.totalSlots());
    assertEquals(0, layout.screenOf(7));
    assertEquals(1, layout.screenOf(4_294_967_295L));
    assertEquals(PackLayout.NO_SCREEN, layout.screenOf(8));
    assertEquals(27, layout.stripRows(854));
  }

  @Test
  void readsOneScreenOfOneSlotAndEightScreensOfEightSlots() {
    final PackLayout one = PackLayout.parse(packConstants("0u", "1", "0", 1)).orElseThrow();
    assertEquals(1, one.screens());
    assertEquals(1, one.totalSlots());
    final PackLayout eight = PackLayout.parse(
      packConstants("1u, 2u, 3u, 4u, 5u, 6u, 7u, 8u", "8, 8, 8, 8, 8, 8, 8, 8", "0, 8, 16, 24, 32, 40, 48, 56", 8)
    ).orElseThrow();
    assertEquals(8, eight.screens());
    assertEquals(56, eight.firstSlot(7));
    assertEquals(64, eight.totalSlots());
  }

  @Test
  void aPageFillsTheRowsItsFourThousandPixelsNeed() {
    assertEquals(4096, PackLayout.rowsPerPage(1));
    assertEquals(5, PackLayout.rowsPerPage(854));
    assertEquals(1, PackLayout.rowsPerPage(4096));
    assertEquals(1, PackLayout.rowsPerPage(4097));
    assertEquals(2, PackLayout.rowsPerPage(4095));
  }

  @Test
  void anythingTheServerCouldNotHaveGeneratedIsNoLayout() {
    final String valid = packConstants("7u, 9u", "3, 2", "0, 3", 2);
    for (final String packConstants : List.of(
      "",
      valid.replace("MCV2_SCREENS = 2;", "MCV2_SCREENS = 0;"),
      valid.replace("MCV2_SCREENS = 2;", "MCV2_SCREENS = 9;"),
      valid.replace("MCV2_SCREENS = 2;", "MCV2_SCREENS = 102;"),
      valid.replace("MCV2_SCREENS = 2;", "MCV2_SCREENS = 1;"),
      valid.replace("uint MCV2_SCREEN_STREAMS", "uint MCV2_SCREEN_STREAM"),
      valid.replace("7u, 9u", "7u"),
      valid.replace("7u, 9u", "7, 9u"),
      valid.replace("7u, 9u", "7u, 4294967296u"),
      valid.replace("7u, 9u", "7u, 12345678901u"),
      valid.replace("int[2](3, 2)", "int[2](9, 2)"),
      valid.replace("int[2](3, 2)", "int[2](3, 0)"),
      valid.replace("int[2](3, 2)", "int[2](3, -2)"),
      valid.replace("int MCV2_SCREEN_SLOTS", "int MCV2_SCREEN_SLOT"),
      valid.replace("int[2](0, 3)", "int[2](0, 2)"),
      valid.replace("int[2](0, 3)", "int[2](1, 3)"),
      valid.replace("int[2](0, 3)", "int[2](0, 65)"),
      valid.replace("int MCV2_SCREEN_FIRST_SLOTS", "int MCV2_SCREEN_FIRST")
    )) {
      assertTrue(PackLayout.parse(packConstants).isEmpty(), packConstants);
    }
    assertTrue(PackLayout.parse(valid).isPresent());
  }
}
