plugins {
    `kotlin-dsl`
}

repositories {
    gradlePluginPortal()
    mavenCentral()
}

// the plugins the convention plugins apply; their versions live in gradle/libs.versions.toml, so the module build
// files only name them
dependencies {
    testImplementation(platform(libs.junit.bom))
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)
    testImplementation(gradleTestKit())
    implementation(libs.spotless.gradle)
    implementation(libs.checker.framework.gradle)
    implementation(libs.node.gradle)
    implementation(libs.errorprone.gradle)
    implementation(libs.pitest.gradle)
}

// The coverage lint is also applied to builds that have no version catalog, its TestKit fixtures, so the JaCoCo
// version it pins is compiled into it from the catalog
val catalogVersions = layout.buildDirectory.dir("generated/sources/catalog/kotlin")
val jacocoVersion = libs.versions.jacoco.get()
val generateCatalogVersions = tasks.register("generateCatalogVersions") {
    description = "Writes the catalog versions the plugins of this build need outside the main build"
    inputs.property("jacoco", jacocoVersion)
    outputs.dir(catalogVersions)
    doLast {
        val file = catalogVersions.get().file("me/brandonli/mcav/gradle/CatalogVersions.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |package me.brandonli.mcav.gradle
            |
            |/** Versions from gradle/libs.versions.toml, generated by the build of buildSrc. */
            |object CatalogVersions {
            |    const val JACOCO = "$jacocoVersion"
            |}
            |""".trimMargin()
        )
    }
}

kotlin.sourceSets.main {
    kotlin.srcDir(generateCatalogVersions)
}

tasks.test {
    useJUnitPlatform()
}
